# Generated by Django 4.2.9 on 2024-01-07 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_remove_classroom_student_classroom_classroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='user',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(to='app.student'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher'),
        ),
    ]
